version: 2
jobs:
  unit_test:
    docker:
      # Node 10 LTS
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install -g yarn
      - run: npm run test

  docker_push_master:
    docker:
      # Node 10 LTS
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run docker:build
      - run: npm run docker:push

  docker_push_release:
    docker:
      # Node 10 LTS
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run release:validate
      - run: npm run docker:build:release
      - run: npm run docker:push:release

workflows:
  version: 2
  build_and_push:
    jobs:
      - unit_test:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - unit_test
          filters:
            branches:
              only:
                - master
      - docker_push_release:
          requires:
            - unit_test
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/